# Generated by Django 5.0.7 on 2024-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
