# Generated by Django 5.0.7 on 2024-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_product_image_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_features',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
