# Generated by Django 5.0.6 on 2024-07-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.ImageField(default='', upload_to='profile-images'),
            preserve_default=False,
        ),
    ]
