# Generated by Django 5.0.6 on 2024-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_verification_code_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
